# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "866a91ad229267c43530a41dbbcf9a09"
name = "payment-function-test"
application_url = "https://educational-serve-whole-capitol.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "purple-dot-selling-plans-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_payment_customizations,write_products"

[auth]
redirect_urls = [
  "https://educational-serve-whole-capitol.trycloudflare.com/auth/callback",
  "https://educational-serve-whole-capitol.trycloudflare.com/auth/shopify/callback",
  "https://educational-serve-whole-capitol.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
